# Generated by Django 6.0.3 on 2026-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0007_contadorvisitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='activities_adolescents_13_to_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Actividades'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='activities_adults_30_to_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Actividades'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='activities_adults_over_60',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Actividades'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='activities_children_0_to_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Actividades'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='activities_young_adults_18_to_29',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Actividades'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='adolescents_13_to_17_disabled',
            field=models.PositiveIntegerField(default=0, verbose_name='Adolescentes de 13 a 17 años - Personas con discapacidad'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_disabled',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos de 30 a 59 años - Personas con discapacidad'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='adults_over_60_disabled',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos mayores de 60 años - Personas con discapacidad'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='course_attendees_adolescents_13_to_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Asistentes a cursos por adolescentes entre 13 y 17 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='course_attendees_adults_30_to_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Asistentes a cursos por adultos entre 30 y 59 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='course_attendees_adults_over_60',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Asistentes a cursos por adultos mayores de 60 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='course_attendees_children_0_to_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Asistentes a cursos por niños entre 0 y 12 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='course_attendees_young_adults_18_to_29',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Asistentes a cursos por adultos jóvenes entre 18 y 29 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='courses_done_adolescents_13_to_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Cursos realizados por adolescentes entre 13 y 17 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='courses_done_adults_30_to_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Cursos realizados por adultos entre 30 y 59 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='courses_done_adults_over_60',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Cursos realizados por adultos mayores de 60 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='courses_done_children_0_to_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Cursos realizados por niños entre 0 y 12 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='courses_done_young_adults_18_to_29',
            field=models.PositiveIntegerField(default=0, verbose_name='Módulo de Servicios Digitales - Cursos realizados por adultos jóvenes entre 18 y 29 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_disabled',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños de 0 a 12 años - Personas con discapacidad'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adolescents_13_to_17_invalids',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes - Adolescentes entre 13 y 17 años (Personas con discapacidad)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_30_to_59_invalids',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos entre 30 y 59 años (Personas con discapacidad)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_over_60_invalids',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos mayores de 60 hombres - Adultos mayores de 60 años (Personas con discapacidad)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='reading_promotion_children_0_to_12_invalids',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes - Niños entre 0 y 12 años (Personas con discapacidad)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='reading_promotion_young_adults_18_to_29_invalids',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos jóvenes entre 18 y 29 años (Personas con discapacidad)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='total_0_to_12',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Niños entre 0 y 12 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='total_13_to_17',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Adolescentes entre 13 y 17 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='total_18_to_29',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Adultos jóvenes entre 18 y 29 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='total_30_to_59',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Adultos entre 30 y 59 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='total_over_60',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Adultos mayores de 60 años'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_disabled',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos de 18 a 29 años - Personas con discapacidad'),
        ),
        migrations.AlterField(
            model_name='datosestadisticos',
            name='libros_consulta',
            field=models.CharField(default='', max_length=100, verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='datosestadisticos',
            name='libros_general',
            field=models.CharField(default='', max_length=100, verbose_name='General'),
        ),
        migrations.AlterField(
            model_name='datosestadisticos',
            name='libros_infantil',
            field=models.CharField(default='', max_length=100, verbose_name='Infantil'),
        ),
    ]
